### ISSUE TITLE
Read-only mode

### ISSUE THREAD

**Issue by raphaelauv** [DriverX/aioredis-cluster#1]
Hi thank for your work !

I have a cluster with replicas, is there a way to favor read from replicas (follower node) since I could have a read-only cluster client for my app.

**Comment by riya-swagata** [comment]
@raphaelauv  any luck ??... trying to achieve same . so if u have any update it will be help for me..

**Comment by raphaelauv** [comment]
redis-py is now async cluster compliant you should probably use this lib and check this issue -> https://github.com/redis/redis-py/issues/1878
