### ISSUE TITLE
Support decode_responses in initialization / create_redis_cluster

### ISSUE THREAD

**Issue by theblazehen** [DriverX/aioredis-cluster#12]
Passing in a `decode_responses=True` into the create_redis_cluster initializer would be convenient. This would call a `.decode('utf-8')` or similar on all results before returning them

It's currently implemented in both redis-py and aioredis

**Comment by DriverX** [comment]
`aioredis_cluster` supports `encoding` argument in client factories `create_redis_cluster` and `create_cluster`

```python
from aioredis_cluster import create_redis_cluster

redis = await create_redis_cluster(
    [
        ...
    ],
    encoding="utf-8",
)
```

**Comment by theblazehen** [comment]
Ah, I see. Thanks!
